# Generated by Django 5.0.1 on 2024-04-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
